### ISSUE TITLE
Update Bulma

### ISSUE THREAD

**Issue by davidsneighbour** [peaceiris/hugo-mod-bulma#2]
Hi there, novice Bulma user here. I tried to import single SCSS files instead of the `_all` solution you have in your README and two files that are currently listed in the Bulma setup are declared "missing" by Hugo at compilation. It seems this module is affixed to a static Github hash. 

example: https://github.com/jgthms/bulma/tree/master/sass/utilities - extends.scss is not found the other files in that folder are found in this module.

I propose that you introduce versioning, something where we can explicitly select a Bulma version.

**Comment by davidsneighbour** [comment]
Or maybe just run `hugo mod get -u ./...` and create a new release. That should be enough to have the latest master branch version.

**Comment by peaceiris** [comment]
Check a path to your SCSS file.

Here is an example usage: https://github.com/peaceiris/hugo-theme-iris/blob/v0.28.0/assets/theme/scss/bulma.scss

**Comment by davidsneighbour** [comment]
Hi Peaceiris, 

I think you might understand me wrong. What I am doing is the following:

instead of 

```
@import 'mod/bulma/utilities/_all';
```

I do 

```
@import "mod/bulma/utilities/initial-variables";
@import "mod/bulma/utilities/functions";
@import "mod/bulma/utilities/derived-variables";
@import "mod/bulma/utilities/mixins";
@import "mod/bulma/utilities/controls";
@import "mod/bulma/utilities/extends";
```

Which is the content of the current master branch at bulma. The path is ok. ONLY the last line does not get found when I install bulma via your module. So I assume the module version downloaded is an older commit of the repo?

The path is correct, because if I comment out the last line the SCSS builds properly. I added some parameters to my SCSS pipe that set the assets folder as alternative import path, so that's ok.

**Comment by peaceiris** [comment]
I got it.

Today, the latest release of Bulma is `0.9.1`. The `extends` is new file of the bulma's master branch. This repository follows only stable tags, not a default branch.

- master: https://github.com/jgthms/bulma/tree/4871a6a564537435902e9e9af6e12b14e7299a9a/sass/utilities
- https://github.com/jgthms/bulma/tree/0.9.1/sass/utilities

Wait for the next release!

**Comment by peaceiris** [comment]
https://github.com/peaceiris/hugo-mod-bulma/releases/tag/v0.2.0 has been released now.
